name: Build Flutter APK

# Menjalankan build otomatis setiap ada push ke branch main atau master
on:
  push:
    branches:
      - main
      - master

jobs:
  build:
    name: Build APK
    runs-on: ubuntu-latest

    steps:
      # 1. Mengambil kode dari repository menggunakan versi v4 (Terbaru)
      - name: Checkout Repository
        uses: actions/checkout@v4

      # 2. Menyiapkan Java (Dibutuhkan untuk build Android) menggunakan versi v4
      - name: Setup Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      # 3. Menyiapkan instalasi Flutter di server GitHub
      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          # Pastikan channel 'stable' digunakan agar mendownload versi terbaru dan paling aman
          channel: 'stable'

      # 4. Mendownload semua package yang kita atur di pubspec.yaml
      - name: Install Dependencies
        run: flutter pub get

      # 5. Membuat file APK
      - name: Build APK Release
        run: flutter build apk --release

      # 6. Mengunggah file APK menggunakan artifact versi v4 (Terbaru)
      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: qiyam-release-apk
          path: build/app/outputs/flutter-apk/app-release.apk
