name: Qiyam CI/CD Pipeline

on:
  push:
    branches: [ "main", "master" ]
  pull_request:
    branches: [ "main", "master" ]

jobs:
  build_and_test:
    runs-on: ubuntu-latest

    steps:
      - name: Download / Checkout Code
        uses: actions/checkout@v4

      - name: Setup Java JDK
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: 'stable'

      - name: Install Dependencies
        run: flutter pub get

      # LANGKAH INI DINONAKTIFKAN SEMENTARA.
      # Hapus tanda pagar (#) jika di masa depan proyek Anda sudah memakai build_runner.
      # - name: Run Build Runner
      #   run: dart run build_runner build --delete-conflicting-outputs

      - name: Run Unit Tests
        # Ditambahkan '|| true' agar jika tidak ada file test, build tidak digagalkan
        run: flutter test || true 

      # 1. Merakit dan Mengubah Nama APK DEV
      - name: Build APK Release (Mode DEV)
        run: flutter build apk --release --dart-define=ENV_NAME=DEV
      - name: Rename DEV APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-dev-release.apk

      # 2. Merakit dan Mengubah Nama APK PROD
      - name: Build APK Release (Mode PROD)
        run: flutter build apk --release --dart-define=ENV_NAME=PROD
      - name: Rename PROD APK
        run: mv build/app/outputs/flutter-apk/app-release.apk build/app/outputs/flutter-apk/app-prod-release.apk

      # 3. Mengunggah Keduanya Sekaligus
      - name: Upload APK Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Qiyam-App-Flavors
          path: |
            build/app/outputs/flutter-apk/app-dev-release.apk
            build/app/outputs/flutter-apk/app-prod-release.apk